# Site settings
name: DOCTALES
site_title: DOCTALES

title: doctales
email: stefan.eike@mailbox.org
description: doctales is a team of DITA users and developers who share plugins and knowledge to gather and share DITA experience and spread the word.
logo: doctales-logo.svg # 120x120 px default image used for Twitter summary card
teaser: doctales-logo.png # 400x250 px default teaser image used in image archive grid

safe: true
lsi: false
highlighter: rouge
markdown: kramdown
baseurl: ""
sass:
    style: compressed
    sass_dir: _sass

# Disqus
comments :
  provider : disqus
  disqus :
    short_name : doctale